import { useEffect, useRef, useState } from "react";
import { apiUrl } from "../lib/api";

// True-scale AR through <model-viewer> (Apache-2.0): WebXR on Android Chrome, Scene Viewer
// as its fallback, and Quick Look on iOS (model-viewer converts the GLB to USDZ in the
// browser). The model is generated by the API from the work's dimensions and image.
// Where AR is not available the dialog shows the 3D model and points to the room view.
export const AR_UNSUPPORTED_CATEGORIES = ["Sculptures", "Ceramics"];

export function ArView({ artwork, onFallback }) {
  const dialog = useRef(null);
  const viewer = useRef(null);
  const [open, setOpen] = useState(false);
  const [ready, setReady] = useState(false);
  const [canAr, setCanAr] = useState(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    import("@google/model-viewer")
      .then(() => !cancelled && setReady(true))
      .catch(() => !cancelled && setFailed(true));
    return () => {
      cancelled = true;
    };
  }, [open]);

  useEffect(() => {
    const el = viewer.current;
    if (!ready || !el) return;
    const onLoad = () => setCanAr(Boolean(el.canActivateAR));
    const onError = () => setFailed(true);
    el.addEventListener("load", onLoad);
    el.addEventListener("error", onError);
    return () => {
      el.removeEventListener("load", onLoad);
      el.removeEventListener("error", onError);
    };
  }, [ready]);

  if (AR_UNSUPPORTED_CATEGORIES.includes(artwork.category)) return null;
  const d = artwork.dimensions || {};
  const size = d.width
    ? `${d.width} × ${d.height} ${d.unit || "cm"}`
    : "true scale";

  return (
    <>
      <button
        type="button"
        className="text-link ar-link"
        onClick={() => {
          setOpen(true);
          dialog.current?.showModal();
        }}
      >
        See it on your wall <span className="ar-badge">AR</span>
      </button>
      <dialog
        ref={dialog}
        className="ar-dialog"
        aria-labelledby="ar-title"
        onClose={() => setOpen(false)}
      >
        <div className="ar-head">
          <div>
            <span className="eyebrow">AUGMENTED REALITY · {size}</span>
            <h2 id="ar-title">{artwork.title}</h2>
          </div>
          <button
            type="button"
            className="text-link"
            onClick={() => dialog.current?.close()}
          >
            Close
          </button>
        </div>
        <div className="ar-stage">
          {open && ready && !failed ? (
            <model-viewer
              ref={viewer}
              src={apiUrl(`/artworks/${artwork.slug}/model.glb`)}
              alt={`${artwork.title}, shown at true scale`}
              ar
              ar-modes="webxr scene-viewer quick-look"
              ar-placement="wall"
              ar-scale="fixed"
              camera-controls
              camera-orbit="0deg 90deg auto"
              interaction-prompt="none"
              shadow-intensity="0.5"
              environment-image="neutral"
              exposure="1"
              loading="eager"
            >
              <button slot="ar-button" type="button" className="button ar-go">
                Place it on your wall
              </button>
            </model-viewer>
          ) : failed ? (
            <p className="ar-note">
              The 3D view could not load on this device.
            </p>
          ) : (
            <p className="ar-note" aria-live="polite">
              Preparing the work at true scale…
            </p>
          )}
        </div>
        <p className="ar-note">
          {canAr
            ? "Point your camera at a wall. The work appears at its real size; move closer or step back to judge it."
            : "AR opens on a phone or tablet: on this screen you can turn the work in 3D."}{" "}
          <button
            type="button"
            className="link-button"
            onClick={() => {
              dialog.current?.close();
              onFallback?.();
            }}
          >
            Use the room view instead
          </button>
        </p>
      </dialog>
    </>
  );
}
