import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import crypto from 'crypto';import {User} from '../models/index.js';import {env} from '../config/env.js';import {AppError} from '../lib/errors.js';
import {signTokens,randomToken,hashToken} from './tokenService.js';
const issue=signTokens;
export async function register(input){if(await User.exists({email:input.email}))throw new AppError(409,'An account with that email exists','EMAIL_EXISTS');const verificationToken=randomToken();const user=await User.create({...input,passwordHash:await bcrypt.hash(input.password,12),verificationTokenHash:hashToken(verificationToken),verificationExpiresAt:new Date(Date.now()+24*3600e3)});const tokens=issue(user);user.refreshTokens=[await bcrypt.hash(tokens.refreshToken,10)];await user.save();return {user,tokens,verificationToken:process.env.NODE_ENV==='development'?verificationToken:undefined}}
export async function login({email,password}){const user=await User.findOne({email});if(!user||!await bcrypt.compare(password,user.passwordHash))throw new AppError(401,'Invalid email or password','INVALID_CREDENTIALS');const tokens=issue(user);user.refreshTokens=[...(user.refreshTokens||[]).slice(-4),await bcrypt.hash(tokens.refreshToken,10)];await user.save();return {user,tokens}}

export async function requestPasswordReset(email){const user=await User.findOne({email});if(!user)return;const token=randomToken();user.passwordResetTokenHash=hashToken(token);user.passwordResetExpiresAt=new Date(Date.now()+30*60e3);await user.save();return process.env.NODE_ENV==='development'?token:undefined}
export async function resetPassword(token,password){const user=await User.findOne({passwordResetTokenHash:hashToken(token),passwordResetExpiresAt:{$gt:new Date()}});if(!user)throw new AppError(400,'Reset link is invalid or expired','INVALID_RESET_TOKEN');user.passwordHash=await bcrypt.hash(password,12);user.passwordResetTokenHash=undefined;user.passwordResetExpiresAt=undefined;user.refreshTokens=[];await user.save()}
export async function verifyEmail(token){const user=await User.findOne({verificationTokenHash:hashToken(token),verificationExpiresAt:{$gt:new Date()}});if(!user)throw new AppError(400,'Verification link is invalid or expired','INVALID_VERIFICATION_TOKEN');user.verified=true;user.verificationTokenHash=undefined;user.verificationExpiresAt=undefined;await user.save();return user}
